version: "3.9"
services:
  app:
    container_name: smop-frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: dev
    ports:
      - 3000:3000
    volumes:
      - .:/home/app
      - /home/app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
