export const en = {
    /* apps */
    'apps.admin': 'SMOP Admins',
    'apps.users': 'SMOP Users',
    /* profiles */
    'profiles.root': 'Root',
    'profiles.admin': 'Administrator',
    'profiles.manager': 'Manager',
    'profiles.auxiliar': 'Auxiliar',
    'profiles.cashier': 'Cashier',
    'profiles.waiter': 'Waiter',
    /* order types */
    'ordertypes.pickup': 'Pick up',
    'ordertypes.curbside': 'Curbside',
    'ordertypes.delivery': 'Delivery',
    'ordertypes.dine-in': 'Dine in',
    /* apply charge */
    'applycharge.0': 'After discount',
    'applycharge.1': 'Before discount',
    /* day */
    'day.opening': 'Opening',
    'day.closing': 'Closing',
    'day.weekday': 'Weekday',
    'day.sunday': 'Sunday',
    'day.monday': 'Monday',
    'day.tuesday': 'Tuesday',
    'day.wenesday': 'Wenesday',
    'day.thursday': 'Thursday',
    'day.friday': 'Friday',
    'day.saturday': 'Saturday',
    /* time */
    'time.hours': 'Hours',
    'time.minutes': 'Minutes',
    /* longitude */
    'longitude.miles': 'Miles',
    /* actions */
    'actions.goback': 'Go back',
    'actions.open': 'Open',
    'actions.close': 'Close',
    'actions.cancel': 'Cancel',
    'actions.new': 'Create new',
    'actions.save': 'Save',
    'actions.edit': 'Edit',
    'actions.update': 'Update',
    'actions.clean': 'Clean up',
    'actions.filter': 'Filter',
    'actions.suspend': 'Suspend',
    'actions.restore': 'Restore',
    'actions.detail': 'Detail',
    'actions.link': 'Link',
    'actions.unlink': 'Unlink',
    'actions.more': 'Actions',
    'actions.prevstep': 'Previous step',
    'actions.nextstep': 'Next step',
    'actions.changelanguage': 'Change language',
    'actions.logout': 'Logout',
    'actions.pwrecovery': 'Password Recovery',
    'actions.activate': 'Activate',
    'actions.deactivate': 'Deactivate',
    /* messages */
    'messages.activate': '',
    'messages.deactivate': '',
    /* filter */
    'filter.name': 'filter by name',
    'filter.status': 'filter by status',
    'filter.fromdate': 'from creation date',
    'filter.todate': 'to creation date',
    'filter.profile': 'filter by profile',
    /* headers */
    'headers.name': 'Name',
    'headers.created': 'Created',
    'headers.status': 'Status',
    'headers.actions': 'Actions',
    'headers.amount': 'Amount',
    'headers.profile': 'Profile',
    'headers.contacts': 'Contacts',
    /* status */
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    /* nav links */
    'links.home': 'Home',
    'links.organizations': 'Organizations',
    'links.organization': 'Organization',
    'links.commerces': 'Commerces',
    'links.users': 'Users',
    'links.shelf': 'Product shelf',
    'links.titles': 'Menu titles',
    'links.addons': 'Menu addons',
    'links.products': 'Products',
    /* views */
    /* auth views */
    'auth.email.placeholder': 'User email',
    'auth.email.required': 'user email is required',
    'auth.email.format': 'invalid email format',
    'auth.password.placeholder': 'User password',
    'auth.password.hint': 'uppercase, lowercase & special character @$!%*?&',
    'auth.password.required': 'user password is required',
    'auth.password.min': 'password must contain at least 8 characters',
    'auth.password.max': 'password must contain up to 15 characters',
    'auth.password.format': 'special character @$!%*?&, uppercase & lowercase',
    'auth.currentpassword.placeholder': 'Current password',
    'auth.currentpassword.required': 'current password is required',
    'auth.newpassword.placeholder': 'New password',
    'auth.newpassword.required': 'new password is required',
    'auth.repeatpassword.placeholder': 'Confirm password',
    'auth.repeatpassword.required': 'password confirmation is required',
    'auth.repeatpassword.equal': 'new password and confirmation must match',
    /* sign in view */
    'signin.title': 'Sign in',
    'signin.actions.signin': 'Sign in',
    'signin.actions.recovery': 'Password recovery',
    /* reset password view */
    'resetpassword.title': 'Reset password',
    'resetpassword.actions.reset': 'Reset password',
    /* organizations view */
    'organizations.title': 'Organization list',
    /* create organization view */
    'createorg.title': 'Create organization',
    'createorg.schema.placeholder': 'Organization schema name',
    'createorg.schema.hint': 'lowercase alphabets only',
    'createorg.schema.required': 'organization schema name is required',
    'createorg.schema.alphabets': 'lowercase alphabets only',
    'createorg.name.placeholder': 'Full name',
    'createorg.name.hint': 'organization administrator',
    'createorg.name.required': 'full name is required',
    'createorg.email.hint': 'click on @ to generate email',
    'createorg.email.generate': 'Click here to generate email',
    /* organization detail view */
    'orgdetail.title': 'Organization detail',
    'orgdetail.references': 'References',
    'orgdetail.orgname': 'Organization name',
    'orgdetail.owner': 'Owner',
    'orgdetail.settings': 'Settings',
    'orgdetail.decimals': 'Decimals',
    'orgdetail.languages': 'Accepted languages',
    'orgdetail.branding': 'Branding',
    /* organization edit */
    'orgedit.references': 'Update references',
    'orgedit.org.placeholder': 'Organization name',
    'orgedit.org.hint': 'organization reference name',
    'orgedit.org.required': 'organization name is required',
    'orgedit.owner.placeholder': 'Owner name',
    'orgedit.owner.hint': 'owner reference name',
    'orgedit.owner.required': 'owner name is required',
    'orgedit.settings': 'Update settings',
    'orgedit.decimals.placeholder': 'Prices decimals from 1 up to 4',
    'orgedit.decimals.hint': 'amount of decimals for prices',
    'orgedit.decimals.integer': 'only integers',
    'orgedit.decimals.min': 'min amount: 1',
    'orgedit.decimals.max': 'max amount: 4',
    'orgedit.languages.description': 'feature in working process',
    'orgedit.languages.hint': 'Multilanguage support',
    'orgedit.branding': 'Update branding',
    'orgedit.cover.hint': 'branding cover',
    'orgedit.cover.required': 'branding cover is required',
    'orgedit.cover.size': 'file cover size up to 10MB',
    'orgedit.cover.type': 'file cover type allowed: jpg / png',
    'orgedit.cover.remove': 'Remove cover file',
    'orgedit.profile.hint': 'branding profile',
    'orgedit.profile.required': 'branding profile is required',
    'orgedit.profile.size': 'file profile size up to 10MB',
    'orgedit.profile.type': 'file profile type allowed: jpg / png',
    'orgedit.profile.remove': 'Remove profile file',
    /* commerce list view */
    'commercelist.title': 'Commerce list',
    'commercelist.updatestatus': 'Update commerce status',
    /* commerce detail view */
    'commercedetail.title': 'Commerce detail',
    'commercedetail.references': 'References',
    'commercedetail.name': 'Commerce name',
    'commercedetail.address': 'Address',
    'commercedetail.optaddress': 'Optional address',
    'commercedetail.zipcode': 'ZIP code',
    'commercedetail.phones': 'Phone numbers',
    'commercedetail.geoinfo': 'Geographic information',
    'commercedetail.country': 'Country',
    'commercedetail.state': 'State',
    'commercedetail.city': 'City',
    'commercedetail.timezone': 'Time zone',
    'commercedetail.gtmoffset': 'GTM offset',
    'commercedetail.settings': 'Order settings',
    'commercedetail.online': 'Do you accept order online right now?',
    'commercedetail.orders': 'Allowed order types',
    'commercedetail.charge': 'Order online charge',
    'commercedetail.typecharge': 'Type charge',
    'commercedetail.percentagecharge': 'by percentage',
    'commercedetail.amountcharge': 'by amount',
    'commercedetail.applycharge': 'Apply charge',
    'commercedetail.sms': 'Order alerts by SMS?',
    'commercedetail.deliveries': 'Delivery settings',
    'commercedetail.third': 'Allow third party delivery?',
    'commercedetail.thirdsite': 'Third party delivery web site',
    'commercedetail.mindelivery': 'Min amount delivery',
    'commercedetail.deliveryarea': 'Delivery area',
    'commercedetail.attention': 'Attention settings',
    'commercedetail.onsite': 'On site attention',
    'commercedetail.onsitepreparation': 'On site preparation time',
    'commercedetail.delivery': 'Delivery attention',
    'commercedetail.deliverypreparation': 'Delivery preparation time',
    /* commerce edit */
    'commerceedit.references': 'Update references',
    'commerceedit.': '',
};
